# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Antoine Feylessoufi
tagline:          ''
description:      'Assistant Professor at Vanderbilt University'
url:              
baseurl:          /

author:
  name:           'Antoine Feylessoufi'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           <!-- https://github.com/poole/hyde -->
